import { CatchAsyncError } from "../middleware/catchAsyncError";
import { Response, Request, NextFunction } from "express";
import ErrorHandler from "../utils/ErrorHandler";
import OrderModel, { IOrder } from "../models/order.model";
import UserModel from "../models/user.model";
import cloudinary from "cloudinary";
import { redis } from "../utils/redis";
import mongoose from "mongoose";
import path from "path";
import ejs from "ejs";
import sendMails from "../utils/sendMails";
